DATETIME: 6/18/2018 7:28:56 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/18/2018 7:29:44 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1; EXCEPTION: Exception of type 'System.Exception' was thrown.; INNER EXCEPTION: 
DATETIME: 6/18/2018 7:31:28 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/18/2018 7:32:33 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1; EXCEPTION: Exception of type 'System.Exception' was thrown.; INNER EXCEPTION: 
DATETIME: 6/18/2018 7:34:39 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 10:01:16 AM; METHOD: CheckIfUserExistsInDB; REPO: User; EXCEPTION: The underlying provider failed on Open.; INNER EXCEPTION: System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass4.<<ExecuteAsync>b__3>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<OpenAsync>d__8.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20; STACKTRACE:    at System.Data.Entity.Core.EntityClient.EntityConnection.<OpenAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<EnsureConnectionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<GetResultsAsync>d__e.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.<FirstMoveNextAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.UsersRepository.<CheckIfUserExistsInDB>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\UsersRepository.cs:line 44
DATETIME: 6/19/2018 10:02:05 AM; METHOD: CheckIfUserExistsInDB; REPO: User; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.UsersRepository.<CheckIfUserExistsInDB>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\UsersRepository.cs:line 44
DATETIME: 6/19/2018 10:02:05 AM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: PUT; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 10:03:42 AM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 11:46:48 AM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 11:47:12 AM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 11:47:20 AM; METHOD: SelectByOktaId; REPO: User; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.UsersRepository.<SelectByOktaId>d__5.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\UsersRepository.cs:line 64
DATETIME: 6/19/2018 11:47:20 AM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 11:52:21 AM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:21:30 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:23:59 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:36:27 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:36:58 PM; ROUTE: api/TrainingCourses; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:31 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:48 PM; ROUTE: api/TrainingCourses; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:53 PM; ROUTE: api/TrainingCourseModules/{iTrainingCourseId}/Modules; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:53 PM; ROUTE: api/TrainingCourses/{id}; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:57 PM; ROUTE: api/TrainingCourseModuleSections/{iTrainingCourseModuleId}/TrainingCourseModule; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:37:57 PM; ROUTE: api/TrainingCourseModules/{id}; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:09 PM; ROUTE: api/TrainingCourseModuleQuizs/{iTrainingCourseModuleId}/TrainingCourseModule; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:13 PM; ROUTE: api/QuizSheets; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:13 PM; ROUTE: api/QuizQuestions/{iModuleQuizId}/TrainingCourseModuleQuiz; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:13 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:15 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:17 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:18 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:20 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:21 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:23 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:38:24 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:42:09 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 12:42:11 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 12:42:11 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 3:55:11 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 3:55:20 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:00:23 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:00:38 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:01:58 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:02:03 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:02:27 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:02:27 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:02:41 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:02:41 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:39 PM; ROUTE: api/TrainingCourses; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:39 PM; ROUTE: api/Users/{sOktaId}/Check; METHOD: PUT; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:39 PM; ROUTE: api/Users/{sOktaId}/Okta; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:41 PM; ROUTE: api/TrainingCourseModules/{iTrainingCourseId}/Modules; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:41 PM; ROUTE: api/TrainingCourses/{id}; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:43 PM; ROUTE: api/TrainingCourseModuleQuizs/{iTrainingCourseModuleId}/TrainingCourseModule; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:45 PM; ROUTE: api/QuizSheets; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:45 PM; ROUTE: api/QuizQuestions/{iModuleQuizId}/TrainingCourseModuleQuiz; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:45 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:47 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:48 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:50 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:52 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:53 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:55 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:08:56 PM; ROUTE: api/QuizQuestionAnswerOptions/{iQuizQuestionId}/QuizQuestion; METHOD: GET; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:09:18 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:12:56 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:13:55 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:14:21 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:16:22 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:16:22 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:16:32 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:17:29 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:17:29 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:17:35 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:17:44 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:17:44 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:18:02 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:18:39 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:18:39 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:19:13 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:19:56 PM; METHOD: SelectByuizQuestion; REPO: QuizQuestionCorrectAnswer; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: ; STACKTRACE:    at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MGCTrainingPortalAPI.Repository.QuizQuestionCorrectAnswerRepository.<SelectByQuizQuestion>d__4.MoveNext() in C:\EntellicationSoftware\Projects\MGCTrainingPortalAPI\Repository\QuizQuestionCorrectAnswerRepository.cs:line 53
DATETIME: 6/19/2018 4:19:56 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Sequence contains no elements; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:20:38 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:20:38 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:20:57 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Object reference not set to an instance of an object.; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:20:57 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Object reference not set to an instance of an object.; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:21:10 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
DATETIME: 6/19/2018 4:22:50 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1; EXCEPTION: Object reference not set to an instance of an object.; INNER EXCEPTION: 
DATETIME: 6/19/2018 4:26:03 PM; ROUTE: api/TrainingCourseQuizScores/QuizGrade; METHOD: POST; IP_ADDRESS: ::1
